# Site settings
title: "Foresight Engineering"
email: info@foresightengineering.com.au
subtitle: ""
description: Practical, reliable and efficient engineering solutions
#cover: cover.png
#logo: logo.png
#ogol: ogol.png
#icon: icon.png
company: "Foresight Engineering Pty Ltd"
baseurl: ""
url: "http://www.foresightengineering.com.au/"

# Build settings
markdown: kramdown

include:     ['.htaccess']
exclude:     ['vendor','Rakefile','Gemfile','Gemfile.lock','CNAME', 'projects.html']

collections:
- services
- personnel

#
# jekyll-assets: see more at https://github.com/ixti/jekyll-assets
#
assets:

  dirname: assets
  baseurl: /foresight/assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
